### ISSUE TITLE
Multiple `.badge-inline` margin

### ISSUE THREAD

**Issue by iamandrewluca** [creativetimofficial/argon-design-system#23]
https://github.com/creativetimofficial/argon-design-system/blob/4b9606aaa1b471e344dfc3a2cb971598f3f3226e/assets/scss/custom/_badge.scss#L26-L29

When having multiple `.badge-inline`, last one has additional `margin-right`

![image](https://user-images.githubusercontent.com/1881266/45408366-d7560300-b674-11e8-9e4e-8f01f5e5f7fe.png)

Replacing that block with this one, will fix the problem

```css
 .badge-inline + .badge-inline { 
     margin-left: .625rem; 
 } 
```
![image](https://user-images.githubusercontent.com/1881266/45408461-11bfa000-b675-11e8-8964-a5d2fd4b138b.png)
